### ISSUE TITLE
How to add support here React Router 4

### ISSUE THREAD

**Issue by gHashTag** [mauricedb/server-side-rendering-with-create-react-app#1]
Very interesting solution, but how to add support to it React Router 4
This is [docs](https://reacttraining.com/react-router/web/guides/server-rendering) 

 ```javascript
const context = {}

  const html = ReactDOMServer.renderToString(
    <StaticRouter
      location={req.url}
      context={context}
    >
      <App/>
    </StaticRouter>
  )

**Comment by mauricedb** [comment]
@gHashTag 

Sorry for the delay, missed your message for some reason.

Ust add the `StaticRouter` code snippet [here](https://github.com/mauricedb/server-side-rendering-with-create-react-app/blob/master/src/index.ssr.js).

You will need to change the code [here](https://github.com/mauricedb/server-side-rendering-with-create-react-app/blob/master/server/react-app.js#L23). Last time I checked using `renderToNodeStream(reactElement)` didn't work with the StaticRouter context. And logically it coudn't really because by the time you can check `context.url` for a redirect most of the page has been streamed to the client.

```
const context = {};
const markup = renderToString(reactElement);

if (context.url) {
  // Somewhere a `<Redirect>` was rendered
  redirect(301, context.url);
} else {
  re.write(markup);
}
```
